name: Actualizar Canales JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # Todos los días a las 6 AM UTC

jobs:
  update-channels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Run channel scraper
        run: python scraper.py
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(channels): Actualización automática de canales"
          file_pattern: 'canales.json'
