name: Actualizar Contenidos de la App

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Todos los días a las 06:00 UTC

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run channel scraper
        run: python scraper.py

      - name: Run agenda scraper
        run: python agenda_scraper.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |
            🔄 Actualización automática de canales y agenda
          file_pattern: |
            canales.json
            eventos.json
