name: Actualizar Canales JSON

# Disparadores: Se ejecuta automáticamente todos los días a las 06:00 UTC
# y también se puede ejecutar manualmente desde la pestaña Actions.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      # 1. Clona el repositorio para tener acceso a los archivos
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura el entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Instala las librerías que necesita el script
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4. Ejecuta el script de scraping
      - name: Run scraper
        run: python scraper.py

      # 5. Guarda los cambios en el repositorio si el archivo canales.json cambió
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Actualización automática de canales"
          file_pattern: 'canales.json'
