name: Actualizar Contenidos de la App

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      # Este paso clona tu repositorio para que el robot pueda acceder a los archivos
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configura el entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Instala las herramientas listadas en requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ejecuta el script de los canales
      - name: Run channel scraper
        run: python scraper.py

      # Ejecuta el script de la agenda
      - name: Run agenda scraper
        run: python agenda_scraper.py

      # Guarda los cambios si los archivos JSON fueron modificados
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Actualización automática de contenidos"
          file_pattern: 'canales.json eventos.json'
