name: Actualizar Contenidos de la App

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # Se ejecuta todos los días a las 6 AM UTC

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      #  PASO 1: Ejecuta el script de los CANALES
      - name: Run channel scraper
        run: python scraper.py

      #  PASO 2: Ejecuta el nuevo script de la AGENDA
      - name: Run agenda scraper
        run: python agenda_scraper.py

      #  PASO 3: Guarda los cambios si CUALQUIERA de los dos archivos cambió
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Actualización automática de contenidos (canales y eventos)"
          file_pattern: 'canales.json eventos.json'
